CREATE TABLE USERS_INFO(
 ID  INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
 USERID VARCHAR(50) NOT NULL UNIQUE,
 NAME VARCHAR(20) NOT NULL,
 PASSWORD VARCHAR(20) NOT NULL
 );

CREATE TABLE CATS_INFO(
 CATID INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
 USERID VARCHAR(50) NOT NULL UNIQUE,
 CATNAME VARCHAR(20) NOT NULL,
 BIRTH DATE NOT NULL,
 GENDER INTEGER NOT NULL,
 WEIGHT INTEGER NOT NULL,
 IMAGE MEDIUM NOT NULL,
 COMMENT VARCHAR(250) NOT NULL,
 REGISTDATE TIMESTAMP NOT NULL
 );
  
CREATE TABLE MESSAGES(
 MESSAGEID INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
 USERID VARCHAR(50) NOT NULL UNIQUE,
 CATID INTEGER,
 MESSAGE VARCHAR(250) NOT NULL
 );
 
drop table USER_INFO
drop table CAT_INFO
drop table MESSAGES
    
